#matthew groover
#1-31-20
#This makefile runs two commands on the same file
#first it updates lex.yy.c by compiling the new
#lab2remove then compiles both into a single executable
lab2remove:lab2remove.l lex.yy.c
	 lex lab2remove.l
	 gcc -o lab2remove lex.yy.c


